# Generated by Django 4.2.7 on 2023-11-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='lang',
            field=models.CharField(choices=[('py', 'Python'), ('cpp', 'C++'), ('js', 'JavaScript')], max_length=30),
        ),
    ]
